### ISSUE TITLE
Circuit Breaker game

### ISSUE THREAD

**Issue by MartinSStewart** [lucamug/3D_Graphics_in_the_Browser_with_Elm#1]
I made a game a year ago in Elm. It uses elm-explorations/webgl so maybe it's appropriate in your article.
Game: https://martinsstewart.gitlab.io/hackman/
Source: https://gitlab.com/MartinSStewart/hackman

Edit: Here's some gameplay footage if needed https://www.dropbox.com/s/tlxeudm5x3wygjq/circuit%20breaker%20gameplay.mov?dl=0

**Comment by lucamug** [comment]
Yes, I actually it several times and is very cool. Somehow I missed it. I will add
